[[language]]
name = "glimmer"
scope = "source.glimmer"
injection-regex = "hbs"
file-types = ["hbs"]
block-comment-tokens = { start = "{{!", end = "}}" }
roots = ["Cargo.toml", "Cargo.lock"]
grammar = "glimmer"
language-servers = []
formatter = { command = "prettier", args = ['--parser', 'angular'] }
auto-format = true
