# [[language]]
# name = "glimmer"
# scope = "source.glimmer"
# injection-regex = "hbs"
# indent = { tab-width = 2, unit = "  " }
# file-types = ["hbs"]
# block-comment-tokens = { start = "{{!", end = "}}" }
# roots = ["Cargo.toml", "Cargo.lock"]
# grammar = "glimmer"
# language-servers = ["vscode-html-language-server", "tailwindcss-ls", "codebook"]
# formatter = { command = "superhtml", args = ["fmt", "--syntax-only", "--stdin"]}
# auto-format = true

# [[language]]
# name = "html"
# formatter = { command = "prettier", args = ["--parser", "jinja-template", "--stdin-filepath=%{buffer_name}"]}
# auto-format = true
# language-servers = ["vscode-html-language-server", "codebook", "tailwindcss-ls"]

# [[language]]
# name = "html"
# formatter = { command = "superhtml", args = ["fmt", "--syntax-only", "--stdin"]}
# auto-format = true
# language-servers = ["vscode-html-language-server", "tailwindcss-ls", "angular", "codebook"]

